"""add_error_message_to_documents

Revision ID: 65b8a86f67d0
Revises: c914c2d13626
Create Date: 2026-02-18 05:15:26.484865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b8a86f67d0'
down_revision: Union[str, Sequence[str], None] = 'c914c2d13626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'error_message')
    # ### end Alembic commands ###
